name: Deploy to Production

# Only trigger deployment on push to main branch
on:
  push:
    branches:
      - main
  # Explicitly exclude pull requests
  pull_request: null

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Only run if this is a push to main (extra safety check)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Build application
        run: yarn build
        env:
          # Add your environment variables here if needed
          NODE_ENV: production

      # Uncomment and configure if using Firebase App Hosting
      # - name: Deploy to Firebase App Hosting
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     projectId: 'your-firebase-project-id'
      #     channelId: live

      # Uncomment if using Vercel
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.ORG_ID }}
      #     vercel-project-id: ${{ secrets.PROJECT_ID }}
      #     vercel-args: '--prod'
