name: PR Linting

on:
  pull_request:
    branches:
      - main
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run commitlint
        run: |
          npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }} --verbose

  prlint-reloaded:
    runs-on: ubuntu-latest

    steps:
      - uses: maor-rozenfeld/prlint-reloaded@v1
        with:
          title-regex: "^MH-\\d+:\\s[A-Z]"
          error-message: 'Your title must be in the format MH-{number}: Description (e.g., MH-123: Add new feature).'

      - uses: maor-rozenfeld/prlint-reloaded@v1
        with:
          title-regex: "^MH-\\d+:\\s\\S+(\\s+\\S+)*"
          error-message: 'Your title must have text after the colon'

      - uses: maor-rozenfeld/prlint-reloaded@v1
        with:
          title-regex: "^MH-\\d+:\\s(?![A-Z][a-z]*ing\\s)(?![A-Z][a-z]*ed\\s)[A-Z]"
          error-message: "Use imperative mood (e.g., 'Add', not 'Adding' or 'Added')"
